techieOrganization/techie

- .idea/encodings.xml
- back-end/build.gradle
- back-end/src/main/java/com/techie/backend/video/controller/VideoController.java
- back-end/src/main/java/com/techie/backend/video/repository/VideoRepository.java
- back-end/src/main/java/com/techie/backend/video/service/VideoService.java
#14 
영상 전체 검색 기능을 개발하였습니다. 
- 검색어를 포함하는 타이틀을 가진 영상들을 응답으로 보냅니다.
- 검색어에 맞는 영상이 없다면 빈 리스트를 반환합니다. 
- VideoController - searchVideo 핸들러 추가
- VideoRepository - 타이틀에 특정 문자열이 포함되는지 기준으로 Video 엔티티를 찾는 findByTitleContaining 추가
- VideoService - videoSearch 메소드를 개발하고, 중복 코드를 extract Method 
- application.yml 에 `server:
servlet:
encoding:
charset: UTF-8
enabled: true
force: true` 추가했습니다. yml이 gitignore 파일이라 수동으로 추가 부탁드립니다. 한글 검색어를 처리하기 위한 인코딩 변경입니다.
> [BE] [#14] 영상 전체 검색 기능 개발 완료

- back-end/src/main/java/com/techie/backend/video/controller/VideoController.java
- back-end/src/main/java/com/techie/backend/video/service/VideoService.java
#23 
VideoService 코드의 가독성을 높이고, 사용하는 외부 라이브러리의 메소드를 변경하였습니다.
또한 예외처리를 추가하였습니다.
- videoSearch(String query)를 fetchVideosByQuery(String query) 로 이름 변경
- JsonProcessingException 처리
- getYoutubeResponse(String videoIds) 에서 요청 url 빌드와 api 요청 전송을 한번에 하도록 변경
- ObjectMapper의 readValue 대신 treeToValue 사용
어떤 변경 사항이 있나요?
> [BE] [#23] VideoService 코드 리팩토링

- back-end/src/main/java/com/techie/backend/global/config/WebConfig.java
🔗 관련 이슈
#31 
프론트 단에서 발생하는 CORS 문제를 해결하기 위해 webConfig를 추가했습니다.
webConfig 추가
어떤 변경 사항이 있나요?
> [BE] [#31] webConfig 추가

- back-end/src/main/java/com/techie/backend/global/config/ModelMapperConfig.java
- back-end/src/main/java/com/techie/backend/global/security/CustomUserDetailService.java
- back-end/src/main/java/com/techie/backend/global/security/CustomUserDetails.java
- back-end/src/main/java/com/techie/backend/global/security/SecurityConfig.java
- back-end/src/main/java/com/techie/backend/user/controller/UserController.java
- back-end/src/main/java/com/techie/backend/user/domain/User.java
- back-end/src/main/java/com/techie/backend/user/dto/UserRequest.java
- back-end/src/main/java/com/techie/backend/user/dto/UserResponse.java
- back-end/src/main/java/com/techie/backend/user/repository/UserRepositoryImpl.java
- back-end/src/main/java/com/techie/backend/user/service/UserService.java
- back-end/src/main/java/com/techie/backend/user/service/UserServiceImpl.java
🔗 관련 이슈
#35
- 로그인에 성공한 유저의 정보를 조회, 수정, 탈퇴를 구현
어떤 변경 사항이 있나요?
> [BE] [#35] 로그인에 성공한 유저의 정보 조회, 수정, 탈퇴 기능 추가

- back-end/src/main/java/com/techie/backend/global/security/SecurityConfig.java
> [BE] refactor: config 설정 복구

- back-end/src/main/java/com/techie/backend/global/security/SecurityConfig.java
- back-end/src/main/java/com/techie/backend/user/controller/UserController.java
- back-end/src/main/java/com/techie/backend/user/domain/User.java
- back-end/src/main/java/com/techie/backend/user/dto/UserRequest.java
- back-end/src/main/java/com/techie/backend/user/dto/UserResponse.java
- back-end/src/main/java/com/techie/backend/user/service/UserService.java
- back-end/src/main/java/com/techie/backend/user/service/UserServiceImpl.java
CrossOrigin 어노테이션 추가
어떤 변경 사항이 있나요?
> [BE ] CORS 에러 해결을 위한 테스트

- .husky/pre-commit
- front-end/.husky/pre-commit
#56 
- husky 실행 안되는 오류 해결하였습니다.
어떤 변경 사항이 있나요?
> [FE] [#56] 프론트 husky 문제 해결

- front-end/src/app/mypage/page.tsx
- front-end/src/styles/common/layout/_grid.scss
- front-end/src/styles/pages/mypage/mypage.scss
#37
- 마이페이지 회원수정 부문 퍼블리싱 완료했습니다.
어떤 변경 사항이 있나요?
> [FE] [#37] 마이페이지 퍼블리싱

- front-end/@types/global.d.ts
- front-end/next.config.mjs
- front-end/package-lock.json
- front-end/package.json
- front-end/src/app/login/page.tsx
- front-end/src/app/signup/page.tsx
- front-end/src/libs/api/registerUserApi.ts
- front-end/src/styles/common/components/_colors.scss
- front-end/src/styles/pages/login/login.scss
- front-end/src/styles/pages/register/register.scss
- front-end/tsconfig.json
- front-end/yarn.lock
#38
#51
• 클라이언트에서 제공하는 정보들을 백엔드 서버로 POST
• 회원가입 로그인 페이지 UI 수정
어떤 변경 사항이 있나요?
> [FE] [#38] 회원가입 백엔드 연결 / 환경 변수 설정

- back-end/src/main/java/com/techie/backend/global/security/JWTFilter.java
- back-end/src/main/java/com/techie/backend/global/security/JWTUtil.java
- back-end/src/main/java/com/techie/backend/global/security/LoginFilter.java
- back-end/src/main/java/com/techie/backend/global/security/UserDetailsCustom.java
- back-end/src/main/java/com/techie/backend/global/security/UserDetailsServiceCustom.java
- back-end/src/main/java/com/techie/backend/user/controller/UserController.java
- back-end/src/main/java/com/techie/backend/user/domain/User.java
- back-end/src/main/java/com/techie/backend/user/dto/UserRequest.java
- back-end/src/main/java/com/techie/backend/user/dto/UserResponse.java
- back-end/src/main/java/com/techie/backend/user/repository/UserRepository.java
- back-end/src/main/java/com/techie/backend/user/service/UserService.java
- back-end/src/main/java/com/techie/backend/user/service/UserServiceImpl.java
#28 
- User 조회, 수정, 탈퇴 기능을 추가하였습니다.
> [BE] [#28] 회원 정보 조회 , 수정 , 탈퇴 기능 추가

- back-end/src/main/java/com/techie/backend/global/exception/ExceptionType.java
- back-end/src/main/java/com/techie/backend/global/exception/GlobalExceptionHandler.java
- back-end/src/main/java/com/techie/backend/global/exception/user/EmptyFieldException.java
- back-end/src/main/java/com/techie/backend/global/exception/user/InvalidEmailFormatException.java
- back-end/src/main/java/com/techie/backend/global/exception/user/PasswordMismatchException.java
- back-end/src/main/java/com/techie/backend/global/exception/user/PasswordTooShortException.java
- back-end/src/main/java/com/techie/backend/global/exception/user/UserAlreadyExistsException.java
- back-end/src/main/java/com/techie/backend/global/exception/user/UserNotFoundException.java
- back-end/src/main/java/com/techie/backend/global/security/LoginFilter.java
- back-end/src/main/java/com/techie/backend/user/dto/UserRequest.java
- back-end/src/main/java/com/techie/backend/user/service/UserServiceImpl.java
#76
- User에 관한 유효성 검사를 추가하였습니다.
- Map<String, String> 형태의 errorResponse를 사용하여 error 키에 예외 메시지를 추가하여 클라이언트가 쉽게 error 메시지를 추출하여 화면에 표시할 수 있도록 하였습니다.
1. 회원가입
- 이메일 중복 확인
- 모든 필드 입력 확인
- 올바른 이메일 형식 확인
- 올바른 비밀번호 형식 확인
- 비밀번호, 비밀번호 확인 값이 일치하는지 확인
2. 로그인
- 데이터베이스에 저장된 데이터와 일치하는지 확인
- 필수 입력란을 모두 입력하였는지 확인
어떤 변경 사항이 있나요?
> [BE] [#76] User 유효성 검사 추가

- back-end/src/main/java/com/techie/backend/video/domain/Category.java
- back-end/src/main/java/com/techie/backend/video/domain/Video.java
- back-end/src/main/java/com/techie/backend/video/service/VideoService.java
- back-end/src/main/resources/db/data.sql
#78 
1. Video 엔티티의 pk를 youtube 영상 id로 변경합니다.
@GeneratedValue 를 지우고, 유튜브 측에서 이미 생성되어있는 유튜브 영상 id를 pk로 사용합니다.
2. Category 추가
1. pk 값을 videoId로 수정하고, 기존의 videoId 필드를 삭제하였습니다.
이에 이어지는 VideoService 메소드들을 수정하였습니다.
2. 아래에 따라 Category 이넘 클래스에 값을 추가하였습니다.
> [BE] [#78] Video pk 변경 및 Category 추가

- front-end/src/app/layout.tsx
- front-end/src/app/login/page.tsx
- front-end/src/app/mypage/page.tsx
- front-end/src/app/signup/page.tsx
- front-end/src/components/ChatbotLayout.tsx
- front-end/src/components/ClientProvider.tsx
- front-end/src/components/Header.tsx
- front-end/src/redux/reducer.ts
- front-end/src/redux/store.ts
#80 
ESlint 설정이 오류가 난 부분을 한번에 확인해보고자 합니다.
어떤 변경 사항이 있나요?
> [FE] [#80] eslint 설정 값 변경

- front-end/package.json
- front-end/src/app/api/userApi.ts
- front-end/src/app/mypage/page.tsx
- front-end/src/components/ClientProvider.tsx
- front-end/src/redux/reducer.ts
- front-end/src/redux/store.ts
- front-end/yarn.lock
#37 
마이페이지 백엔드 api 연결하여, 작업하였습니다.
어떤 변경 사항이 있나요?
> [FE] [#37] 마이페이지 백엔드 연결

- back-end/src/main/java/com/techie/backend/global/exception/GlobalExceptionHandler.java
- GlobalExceptionHandler 클래스 내의 예외처리 메서드들에게서 "message", "status"를 통해서 에러 메시지와 상태코드를 프론트로 통신할 수 있게 하였습니다.
어떤 변경 사항이 있나요?
> [BE] 유효성 검사 front로부터 예외처리 메세지, 상태를 통신할 수 있도록 코드 수정

- .husky/pre-commit
- front-end/src/app/mypage/page.tsx
- front-end/src/types/userInfo.d.ts
#37
- 작업된 마이페이지 API 명세서에 따라 코드를 변경하였습니다.
어떤 변경 사항이 있나요?
> [FE] [#37] 마이페이지 백엔드 기능 구현

- front-end/src/app/signup/page.tsx
- front-end/src/styles/pages/register/register.scss
#93 
• 백엔드에서 구현한 유효성 검사 적용
• 유효하지 않은 형식일 시에 해당하는 오류 메세지를 회원가입 버튼 상단에 노출되도록 하였음.
> [FE] [#93] 유효성 검사 프론트에서 적용

- back-end/src/main/java/com/techie/backend/video/dto/VideoResponse.java
- back-end/src/main/java/com/techie/backend/video/service/VideoService.java
#100 
프론트로 응답할 영상 정보 json에 영상 id 를 추가합니다.
VideoResponse에 videoId 필드를 추가하고, youtube api에서 응답을 받아올 때
id값을 해당 필드에 set 하였습니다.
<br/>
> [BE] [#100] 영상 응답 JSON에 videoId 추가

- front-end/src/app/page.tsx
#113 
- 메인에 있는 개발 항목 리스트 및 강사 리스트를 단순 코드 추가 방식에서 json 호출 방식으로 변경하였습니다.
- 추가된 개발 항목 클라우드도 노출 완료하였습니다.
어떤 변경 사항이 있나요?
> [FE] [#113] 메인 개발 항목 및 강사 리스트 json 호출 방식으로 변경

- front-end/src/app/api/memoAPI.ts
- front-end/src/app/api/videoAPIDetail.ts
- front-end/src/app/layout.tsx
- front-end/src/app/playlists/[category]/[videoId]/page.tsx
- front-end/src/components/axios/apiClient.tsx
- front-end/src/components/playlist/CategoryPlaylist.tsx
- front-end/src/redux/store.ts
- front-end/src/styles/pages/playlist/playlist.scss
#111 
- 메모 기능 백엔드 API 연동하여 pr 생성합니다.
어떤 변경 사항이 있나요?
> [FE] [#119] 메모 백엔드 기능 연결

- back-end/src/main/java/com/techie/backend/video/controller/VideoController.java
- back-end/src/main/java/com/techie/backend/video/service/VideoService.java
#118 
영상 응답을 페이징이 가능하도록 수정하였습니다.
Pageable 객체를 받은 후  `convertJsonToVideoDTO` 메소드에서 요청한 페이징 부분만
VideoResponse 객체로 변환하여, Slice 타입으로 반환하도록 하였습니다.
> [BE] [#118] 영상 응답에 페이징 추가

- back-end/src/main/java/com/techie/backend/memo/controller/MemoController.java
- back-end/src/main/java/com/techie/backend/memo/service/MemoServiceImpl.java
#126 
메모 기본 페이징 사이즈를 20에서 10으로 변경하였습니다. 
`@PageableDefault(size = 10)`  추가
<br/>
> [BE] [#126] 메모 기본 페이징 사이즈 변경

- front-end/src/app/api/memoAPI.ts
- front-end/src/app/api/userApi.ts
- front-end/src/app/api/videoAPI.ts
- front-end/src/app/api/videoAPIDetail.ts
- front-end/src/app/mypage/page.tsx
- front-end/src/app/playlists/[category]/[videoId]/page.tsx
- front-end/src/components/mypage/MyMemoSection.tsx
- front-end/src/components/mypage/MyVideoSection.tsx
- front-end/src/components/mypage/UserInfoSection.tsx
- front-end/src/styles/pages/mypage/mypage.scss
- front-end/src/types/memo.d.ts
#122 
- 마이페이지에서 내가 저장했던 메모들 및 재생목록에 추가란 리스트를 노출시키기 위해 컴포넌트 형식으로 추가하였습니다.
어떤 변경 사항이 있나요?
> [FE] [#122] 마이페이지 컴포넌트 항목들 분리

- front-end/src/app/page.tsx
- front-end/src/components/Header.tsx
- front-end/src/styles/pages/home/home.scss
#124 
- 기존에는 제 플레이리스트로 예시 삼아 노출을 시켜놓은 상태였는데, 백엔드 API 개발이 완료되어 해당 영상 중에 최신 10개의 동영상만 메인 화면에 노출시키고자 합니다.
어떤 변경 사항이 있나요?
> [FE] [#124] 메인 화면 최신 강의 백엔드 API 연결

- front-end/src/app/login/page.tsx
- front-end/src/app/signup/page.tsx
- front-end/src/styles/pages/login/login.scss
- front-end/src/styles/pages/register/register.scss
#19 
• 회원가입 / 로그인 페이지 UI 퍼블리싱 수정
• 마이 페이지와 일관성을 유지하도록 스타일링을 수정하였음.
> [FE] [#19] 회원가입 / 로그인 페이지 퍼블리싱 수정

- front-end/src/app/api/videoAPI.ts
- front-end/src/app/page.tsx
- front-end/src/app/playlists/[category]/page.tsx
- front-end/src/app/playlists/page.tsx
- front-end/src/components/Header.tsx
- front-end/src/components/playlist/CategoryPlaylist.tsx
- front-end/src/data/vidListData.js
- front-end/src/styles/common/layout/_header.scss
- front-end/src/styles/pages/home/home.scss
- front-end/src/styles/pages/playlist/playlist.scss
- front-end/src/types/video.d.ts
#135 
- DB 저장 방식에서 플레이리스트로 변경하여, 수정 완료했습니다.
- 메모 기능 API도 백엔드 비디오 API 변경에 따라 다시 수정이 필요하여, 이 부분도 새로 PR 생성하도록 하겠습니다.
어떤 변경 사항이 있나요?
> [FE] [#135] 백엔드 전체 유튜브 동영상 API 연결 작업

- back-end/src/main/java/com/techie/backend/global/config/ModelMapperConfig.java
- back-end/src/main/java/com/techie/backend/playlist/controller/PlaylistController.java
- back-end/src/main/java/com/techie/backend/playlist/dto/PlaylistRequest.java
- back-end/src/main/java/com/techie/backend/playlist/dto/PlaylistResponse.java
- back-end/src/main/java/com/techie/backend/playlist/service/PlaylistService.java
- back-end/src/main/java/com/techie/backend/playlist/service/PlaylistServiceImpl.java
- back-end/src/main/java/com/techie/backend/playlist_video/repository/PlaylistVideoRepositoryCustom.java
- back-end/src/main/java/com/techie/backend/playlist_video/repository/PlaylistVideoRepositoryImpl.java
- back-end/src/main/java/com/techie/backend/video/domain/Video.java
- back-end/src/main/java/com/techie/backend/video/service/VideoService.java
#141
- 영상 요청 방식을 변경되었기에, 영상을 플레이리스트에 부분적인 코드를 수정하였습니다.
어떤 변경 사항이 있나요?
> [BE] [#141] 플레이리스트 로직 수정

- front-end/src/app/@isLoginChatbot/page.tsx
#91 
• 챗봇의 초기 위치를 수정
• 챗봇의 초기 위치를 디바이스 크기에 맞게 동적으로 렌더링 하도록 수정하였음
> [FE] [#91] 챗봇 초기 위치 수정

- back-end/src/main/java/com/techie/backend/playlist/service/PlaylistServiceImpl.java
#150
- videoId를 통해서 추출한 video 값이 올바르게 db에 저장하지않고 playlist에 출력하여 코드를 수정
> [BE] [#150] video 저장 오류 수정

- front-end/src/components/mypage/MyMemoSection.tsx
- front-end/src/styles/pages/mypage/mypage.scss
- front-end/src/styles/pages/playlist/playlist.scss
#138
- 마이페이지에서 전체 메모가 중복으로 나오던 오류와 영상 디테일 페이지에서 메모 레이아웃을 일부 변경 완료했습니다.
어떤 변경 사항이 있나요?
> [FE] [#138] 메모 기능 오류 수정 및 레이아웃 일부 변경

- back-end/src/main/java/com/techie/backend/playlist/controller/PlaylistController.java
- back-end/src/main/java/com/techie/backend/playlist/service/PlaylistService.java
- back-end/src/main/java/com/techie/backend/playlist/service/PlaylistServiceImpl.java
#141
- playlist 상세조회의 로직을 아래와 같이 수정하였습니다.
1. PathVariable userId 삭제
2. 엔드포인트 수정
3. 그에 따른 메서드 수정
어떤 변경 사항이 있나요?
> [BE] [#144] playlistDetails 코드 수정

- front-end/src/app/api/playlistApi.ts
> [FE]환경변수 수정

- front-end/src/app/@isLoginChatbot/page.tsx
- front-end/src/app/api/playlistApi.ts
> [FE] 플레이리스트 오류 수정 / 챗봇 오류 수정

- front-end/src/app/@isLoginChatbot/page.tsx
> [FE] e.preventDefault(); 위치 수정

- front-end/src/app/@isLoginChatbot/page.tsx
- front-end/src/app/page.tsx
- front-end/src/components/playlist/CategoryPlaylist.tsx
- front-end/src/components/playlist/TeacherPlaylist.tsx
- front-end/src/data/instructorData.js
- front-end/src/styles/pages/mypage/mypage.scss
- front-end/src/styles/pages/playlist/playlist.scss
#166 
- 강사별 리스트 ALL 카테고리 오류 수정
어떤 변경 사항이 있나요?
> [FE] [#116] 강사별 리스트 ALL 카테고리 오류 수정

- front-end/src/app/playlists/[category]/[videoId]/page.tsx
- front-end/src/app/teacher-lists/[category]/[videoId]/page.tsx
타입 오류를 해결하여, PR 생성합니다.
어떤 변경 사항이 있나요?
> [FE] 타입 지정 오류 해결

- front-end/src/app/my-video-list/playlistId/[playlistId]/page.tsx
- front-end/src/components/mypage/MyVideoSection.tsx
• useEffect의 의존성 배열에 토큰값이 추가되지 않아 경고창 발생
• 의존성 배열에 토큰값 정의해 주었음
어떤 변경 사항이 있나요?
> [FE] UseEffect 의존성 배열에 Token값 추가

- front-end/src/app/playlists/[category]/[videoId]/page.tsx
- front-end/src/app/teacher-lists/[category]/[videoId]/page.tsx
- front-end/src/app/teacher-lists/[category]/page.tsx
- front-end/src/components/mypage/MyMemoSection.tsx
- front-end/src/components/playlist/CategoryPlaylist.tsx
- 타입 오류 및 의존성 배열 오류 수정
어떤 변경 사항이 있나요?
> [FE] 타입 오류 및 의존성 배열 오류 수정

- front-end/src/app/my-video-list/playlistId/[playlistId]/page.tsx
- front-end/src/components/mypage/MyVideoSection.tsx
• 빌드시 발생하는 의존성 배열 오류 해결
어떤 변경 사항이 있나요?
> [FE] 빌드시 발생하는 의존성 배열 오류 해결

- front-end/src/components/axios/apiClient.tsx
8080 주소에서 env 주소로 변경했습니다.
어떤 변경 사항이 있나요?
> [FE] 8080 포트 주소 변경

- front-end/src/app/api/playlistApi.ts
- front-end/src/app/my-video-list/playlistId/[playlistId]/page.tsx
- front-end/src/components/playlist/CategoryPlaylist.tsx
- front-end/src/components/playlist/TeacherPlaylist.tsx
- front-end/src/styles/pages/my-video-list/my-video-list.scss
#183 #184 
- 재생목록 내에서 개별의 영상들을 삭제하는 기능
- 빈 재생목록 생성 방지
- 사용자 경험 측면에서 alert 창 비효율적으로 판단하여 제거
- 재생목록 내에서 개별의 영상들을 삭제하는 기능을 구현하였음
- 빈 재생목록을 생성할 수 없도록 하였음
- 사용자 경험 측면에서 alert창 생성이 비효율적으로 판단하여 제거하였음
> [FE] [#183][#184]재생목록 내 개별 영상 삭제 기능구현 / 빈 재생목록 생성 불가 / 사용자경험 측면 alert 창 삭제

- back-end/src/main/java/com/techie/backend/global/AwsHealthCheck.java
#197 
EC2 헬스체크가 제대로 이루어지지않아 헬스체크용 컨트롤러를 따로 만들었습니다. 
/healthCheck 로 들어오는 요청에 200 OK를 보내도록 작업함
> [BE] AWS EC2 HealthCheck용 컨트롤러 생성

- README.md
README에 테키 바로가기 주소를 추가하였습니다. 
[테키 바로가기](https://techie-phi.vercel.app/) 추가
> [BE] [FE] README 파일 수정
